### ISSUE TITLE
Got an Issue running 

### ISSUE THREAD

**Issue by kishan167** [liaralabs/kb-scripts#1]
rtxmlrpc=${HOME}/.local/bin/rtxmlrpc which i dont have that?
plus error on rfr.pl wont connect to 127.0.0.0:58846
tmpdir="${HOME}/tmp/d2r.$$" is saying file already exit

so i am getting other errors but i think if i fix those 2 then it might work can you please help me

Iam running Ubuntu 18.04.4 LTS with Rtorrent 0.9.7 v3.8

**Comment by liaralabs** [comment]
These scripts are for a guide which are not currently public.
